secret_key_base: 03a685e15553adebed5ec6cbc295bdf9b2317fe62bc6d4b7f999a86cd4fe6f69e53636dd85476e02b1285b1fef8c45478a2dd21a3d2801a57f824aa0093c70a88
appliction:
  host: "http://localhost:8000"
priora:
  app_id: app_id
  app_secret: app_secret
  private_key_file: "config/private_key.pem"
  public_key: "config/priora_public_key.pem"
sidekiq:
    port: 6379
    host: "localhost"
    database: 0
    namespace: "connector"
    password: ""
devise:
  secret_key: "test"
